"""Adiciona carga horaria ao curso

Revision ID: 25ead56e65c0
Revises: 4f94d60ca328
Create Date: 2025-08-25 11:42:07.341311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ead56e65c0'
down_revision = '4f94d60ca328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_load', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('course_load')

    # ### end Alembic commands ###
